package com.jbk;
// Generated 14 Mar, 2021 12:39:48 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "record")
public class Country implements java.io.Serializable {

	private Integer cid;
	private String cname;
	private Set students = new HashSet(0);

	public Country() {
	}

	public Country(String cname) {
		this.cname = cname;
	}

	public Country(String cname, Set students) {
		this.cname = cname;
		this.students = students;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cid", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@Column(name = "cname", nullable = false, length = 45)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
//	public Set getStudents() {
//		return this.students;
//	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
