package com.jbk;
// Generated 14 Mar, 2021 12:39:48 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "record")
public class Student implements java.io.Serializable {

	private Integer sid;
	private Country country;
	private String sgread;
	private String sname;

	public Student() {
	}

	public Student(Country country, String sgread, String sname) {
		this.country = country;
		this.sgread = sgread;
		this.sname = sname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sid", unique = true, nullable = false)
	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cid", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "sgread", nullable = false, length = 45)
	public String getSgread() {
		return this.sgread;
	}

	public void setSgread(String sgread) {
		this.sgread = sgread;
	}

	@Column(name = "sname", nullable = false, length = 45)
	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	@Override
	public String toString() {
		return "Student [sid=" + sid + ", country=" + country + ", sgread=" + sgread + ", sname=" + sname + "]";
	}

}
